version: "3.9"

services:
  db:
    image: postgres:0.1
    container_name: postgres
    # restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: 1234.qaz
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_password}
      POSTGRES_DB: myapp
      # POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - db-data:/var/lib/postgresql/data
      # Optional: run init scripts (e.g., create schemas/tables)
      # - ./initdb:/docker-entrypoint-initdb.d:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  pgadmin:
    image: dpage/pgadmin4:0.1
    container_name: pgadmin
    # restart: unless-stopped
    depends_on:
      - db
      # db:
        # condition: service_healthy
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      # PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: admin123
      # PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      # PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      # PGADMIN_CONFIG_LOGIN_BANNER: "Authorized use only"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: